apiVersion : apps/v1
kind: Deployment
metadata:
  name: backendmodel 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backendmodel
  template:
    metadata:
      labels:
        app: backendmodel 
    spec:
      containers:
        - name: backendmodel 
          image: acrcaserestmarcio.azurecr.io/backendmodel
          ports:
          - containerPort: 8000